# Global settings for all VMs
namespace: part2
vmBaseName: rhel-10
imageNamespace: openshift-virtualization-os-images
imageDataSource: rhel10
storageSize: 30Gi
instanceType: u1.medium
preference: rhel.10
machineType: pc-q35-rhel9.6.0

# Scale configuration
vmCount: 7        # Change this number to deploy more or fewer VMs
startSuffix: 1    # Starts at rhel-10-3

# MAC Address configuration 
# The template will dynamically increment the last byte
macBase: "02:9e:b2:01:00"
macStartByte: 17  # Decimal equivalent of Hex '11' (for 02:9e:b2:00:00:11)