apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: part2
  namespace: openshift-gitops
spec:
  destination:
    namespace: part2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo
    repoURL: https://github.com/arslankhanali/ocpvirt-gitops
    targetRevision: HEAD